apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog  
        image: sit722week7na.azurecr.io/book_catalog:v1
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://week07_odmn_user:VgxGG64t0KFhH1qFtxfKSiYAWOyFrVUW@dpg-crppvf0gph6c73a19fr0-a.oregon-postgres.render.com/week07_odmn"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management  
        image: sit722week7na.azurecr.io/inventory_management:v1
        ports:
        - containerPort: 8001
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://week07_odmn_user:VgxGG64t0KFhH1qFtxfKSiYAWOyFrVUW@dpg-crppvf0gph6c73a19fr0-a.oregon-postgres.render.com/week07_odmn"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
